### ISSUE TITLE
1.20.1 Crash

### ISSUE THREAD

**Issue by Krimatoria** [Tigercrl/NonUpdateReloaded#3]
Connector-1.0.0-beta.45+1.20.1.jar
NonUpdateReloaded-1.0.1-forge.jar

I found a problem with the connector, but I'll send them a bug report first) Suddenly it's their mod that's affecting)

**Comment by Tigercrl** [comment]
Try to add the java argument to your launcher's settings: `-Djava.security.manager=allow`

**Comment by Krimatoria** [comment]
> Reference in new

I'll try to check it later)

**Comment by Krimatoria** [comment]
![image](https://github.com/user-attachments/assets/deaa8f04-b565-4a70-b96f-ffdb36ffcb1b)
I still get this error
