### ISSUE TITLE
1.21.1 Crash on startup

### ISSUE THREAD

**Issue by fireboy637** [Tigercrl/NonUpdateReloaded#4]
[latest.log](https://github.com/user-attachments/files/16743669/latest.log)
[crash-2024-08-26_11.31.10-client.txt](https://github.com/user-attachments/files/16743670/crash-2024-08-26_11.31.10-client.txt)

**Comment by Tigercrl** [comment]
Please add the java argument to your launcher's settings: `-Djava.security.manager=allow`
