### ISSUE TITLE
1.21 Crash on game load

### ISSUE THREAD

**Issue by PTALTS-LK** [Tigercrl/NonUpdateReloaded#5]
[crash-2024-08-30_12.49.44-client.txt](https://github.com/user-attachments/files/16811832/crash-2024-08-30_12.49.44-client.txt)
[latest.log](https://github.com/user-attachments/files/16811833/latest.log)

**Comment by Tigercrl** [comment]
Please add the java argument to your launcher's settings: -Djava.security.manager=allow
