### ISSUE TITLE
[1.16.5 Crash] Mod crashed when starting

### ISSUE THREAD

**Issue by GoldenTotem** [Tigercrl/NonUpdateReloaded#8]
Minecraft 1.16.5  Forge 36.2.35  Mod 1.0.1

[Report](https://mclo.gs/n0BBspN)

**Comment by Tigercrl** [comment]
用oracle jdk 8

**Comment by Tigercrl** [comment]
还有问题的话reopen

**Comment by GoldenTotem** [comment]
> 用oracle jdk 8

因为java11也能启动1.16.5，又恐加入整合包中其它玩家也出现此问题而不自知。所以请问此问题的具体信息，以及是否只与java8兼容？

**Comment by GoldenTotem** [comment]
> 还有问题的话reopen

我无法完成reopen，请问能否兼容jdk11？如果不行是否有原因？

**Comment by Tigercrl** [comment]
模组1.16.5版本仅支持jdk8
由于jdk8与jdk11之间部分api已被更改，而本模组使用了反射，可能导致部分类无法找到而报错
